name: CI/CD Pipeline for Python Tkinter Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Specify the version of Python to use

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Uncomment the next line if you have a requirements.txt file
          # pip install -r requirements.txt

      # Step 4: Run a basic script check (non-GUI)
      - name: Run Tkinter script check
        run: |
          python -c "import tkinter; print('Tkinter imported successfully')"
          python -c "from datetime import datetime; print('Datetime imported successfully')"
          # This step ensures there are no syntax or import errors in your script
          python -c """
import tkinter as tk
from datetime import datetime

def calculate_age():
    birth_date = datetime.strptime('2000-01-01', '%Y-%m-%d')
    current_date = datetime.now()
    age = (
        current_date.year
        - birth_date.year
        - ((current_date.month, current_date.day) < (birth_date.month, birth_date.day))
    )
    print(f'Test Age Calculation: {age} years old.')

# Create the main window
root = tk.Tk()
root.title('Age Calculator')

# Create and place widgets
label_birth_date = tk.Label(root, text='Enter your birth date (YYYY-MM-DD):')
label_birth_date.pack()
entry_birth_date = tk.Entry(root)
entry_birth_date.pack()

button_calculate = tk.Button(root, text='Calculate Age', command=calculate_age)
button_calculate.pack()

label_result = tk.Label(root, text='')
label_result.pack()

print('GUI components created successfully.')

# Simulate calling the calculate_age function to test logic
calculate_age()
"""

