name: CI/CD Pipeline for Tkinter Age Calculator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the desired Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Include any additional dependencies if you have a requirements.txt
          # pip install -r requirements.txt

      # Step 4: Run a basic check to ensure the script executes without errors
      - name: Run Tkinter script
        run: |
          python -c "import tkinter; print('Tkinter imported successfully')"
          python age_calculator.py  # Replace 'age_calculator.py' with your script name
