name: Send Email

on:
  push:
    branches:
      - main

jobs:
  send-email:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker container
        run: |
          docker build -t send-email-image .
          docker run -e SMTP_SERVER=smtp.office365.com \
                     -e SMTP_PORT=587 \
                     -e SMTP_USER=satyambhat@aarkglobalinc.com \
                     -e SMTP_PASSWORD=Simple@321 \
                     send-email-image \
                     powershell -Command "C:\sendemail.exe -f your-email@outlook.com -t kanavpreet@aarkglobalinc.com -u 'Subject of the email' -m 'Body of the email' -s smtp.office365.com:587 -xu satyambhat@aarkglobalinc.com -xp Simple@321 -o tls=yes"

    env:
      SMTP_USER: satyambhat@aarkglobalinc.com
      SMTP_PASSWORD: Simple@321
