name: Build Age Calculator
 
on:
  push:
    branches:
      - main  # Adjust branch name as per your main branch
 
jobs:
  build:
    runs-on: windows-latest  # Use windows-latest for Windows instance
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Print current directory
      run: |
        echo "Current working directory: $PWD"
        dir  # List contents of current directory
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Replace with your Python version
    - name: Install dependencies
      run: |
        pip install pyinstaller
    - name: Print current directory
      run: |
        echo "Current working directory: $PWD"
        dir  # List contents of current directory
    - name: Build executable
      run: |
        dir
        pyinstaller --onefile  age_cal.py  # Adjust path as needed
    - name: Print current directory
      run: |
        echo "Current working directory: $PWD"
        dir  # List contents of current directory
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: age_cal_exe
        path: dist/age_cal.exe
