name: Build and Package Application

on:
  push:
    branches:
      - main  # Adjust branch name as per your main branch

jobs:
  build_age_cal_exe:
    runs-on: windows-latest  # Use windows-latest for Windows instance
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Print current directory
      run: |
        echo "Current working directory: $PWD"
        dir  # List contents of current directory
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'  # Replace with your Python version
    - name: Install dependencies
      run: |
        pip install pyinstaller
    - name: Print current directory
      run: |
        echo "Current working directory: $PWD"
        dir  # List contents of current directory
    - name: Build executable
      run: |
        pyinstaller --onefile age_cal.py  # Adjust path as needed
    - name: Print current directory
      run: |
        echo "Current working directory: $PWD"
        dir  # List contents of current directory
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: age_cal_exe
        path: dist/age_cal.exe

  build_inno_setup:
    runs-on: windows-latest  # Use windows-latest for Windows instance
    needs: build_age_cal_exe  # Ensure this job runs after build_age_cal_exe job
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Print current directory
      run: |
        echo "Current working directory: $PWD"
        dir  # List contents of current directory
    - name: Download age_cal.exe artifact
      uses: actions/download-artifact@v3
      with:
        name: age_cal_exe
        path: age_cal  # Specify the directory where age_cal.exe should be downloaded
    - name: Download and install Inno Setup
      run: |
        curl -L -o innosetup.exe "https://jrsoftware.org/download.php/is.exe"
        Start-Process -FilePath "innosetup.exe" -ArgumentList "/VERYSILENT", "/SUPPRESSMSGBOXES", "/NORESTART" -NoNewWindow -Wait
    - name: Print current directory
      run: |
        echo "Current working directory: $PWD"
        dir  # List contents of current directory
    - name: Create Inno Setup script
      run: |
        echo "[Setup]
        OutputBaseFilename=setup
        AppVersion=1.0
        DefaultDirName={pf}\kvapp
        DisableProgramGroupPage=yes
        UninstallDisplayIcon={app}\age_cal.exe
        Compression=lzma
        SolidCompression=yes

        [Files]
        Source: age_cal/age_cal.exe; DestDir: {app}; Flags: ignoreversion
        " > setup_script.iss
    - name: Print current directory
      run: |
        echo "Current working directory: $PWD"
        dir  # List contents of current directory
    - name: Run Inno Setup compiler
      run: |
        Start-Process -FilePath "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" -ArgumentList "setup_script.iss" -NoNewWindow -Wait
    - name: Print current directory
      run: |
        echo "Current working directory: $PWD"
        dir  # List contents of current directory
        dir age_cal
    - name: Upload Inno Setup installer artifact
      uses: actions/upload-artifact@v3
      with:
        name: setup_exe
        path: Output/setup.exe  # Adjust path to setup.exe output file
    - name: List files for debugging
      run: |
        echo "Listing files in current directory:"
        dir
        echo "Listing files in Output directory:"
        dir Output
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'  # Replace with your Python version
    - name: Send email with attachment
      run: |
        python send_email.py "smtp@aarkglobalinc.com" "qqtbzfbxwlxbbkjt" "satyambhat@aarkglobalinc.com" "Workflow finished" "Job completed successfully by GitHub Actions" "Output/setup.exe"
