name: CI/CD Pipeline for Python Calculator

# Define the trigger for the workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs that make up the workflow
jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run tests
      - name: Run tests
        run: |
          python -m unittest discover

      # Step 5: Install PyInstaller
      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      # Step 6: Create executables
      - name: Create executables
        run: |
          dir
          pyinstaller --onefile age_cal.py  # Replace 'your_script.py' with your main script

      # Step 7: Upload executables as artifacts
      - name: Upload executables
        uses: actions/upload-artifact@v3
        with:
          name: executables
          path: dist/*.exe

  deploy:
    runs-on: windows-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Download executables
      - name: Download executables
        uses: actions/download-artifact@v3
        with:
          name: executables
          path: ./dist

      # Step 3: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          dir
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
 
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: age.exe
          
