name: Build and Package Application

on:
  push:
    branches:
      - main  # Adjust branch name as per your main branch

jobs:
  build_age_cal_exe:
    runs-on: windows-latest  # Use windows-latest for Windows instance
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Print current directory
      run: |
        echo "Current working directory: $PWD"
        dir  # List contents of current directory
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'  # Replace with your Python version
    - name: Install dependencies
      run: |
        pip install pyinstaller
    - name: Print current directory
      run: |
        echo "Current working directory: $PWD"
        dir  # List contents of current directory
    - name: Build executable
      run: |
        pyinstaller --onefile age_cal.py  # Adjust path as needed
    - name: Print current directory
      run: |
        echo "Current working directory: $PWD"
        dir  # List contents of current directory
        dir dist  # List contents of dist directory to confirm age_cal.exe is there
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: age_cal_exe
        path: dist/age_cal.exe

  build_inno_setup:
    runs-on: windows-latest  # Use windows-latest for Windows instance
    needs: build_age_cal_exe  # Ensure this job runs after build_age_cal_exe job
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Print current directory
      run: |
        echo "Current working directory: $PWD"
        dir  # List contents of current directory
    - name: Download age_cal.exe artifact
      uses: actions/download-artifact@v3
      with:
        name: age_cal_exe
        path: ./downloaded_artifacts  # Specify the directory where age_cal.exe should be downloaded
    - name: Print current directory
      run: |
        echo "Current working directory: $PWD"
        dir  # List contents of current directory
        dir downloaded_artifacts  # List contents of downloaded_artifacts to confirm age_cal.exe is there
    - name: Download and install Inno Setup
      run: |
        curl -L -o innosetup.exe "https://jrsoftware.org/download.php/is.exe"
        Start-Process -FilePath "innosetup.exe" -ArgumentList "/VERYSILENT", "/SUPPRESSMSGBOXES", "/NORESTART" -NoNewWindow -Wait
    - name: Create Inno Setup script
      run: |
        echo "[Setup]
        OutputDir=Output
        OutputBaseFilename=setup
        AppVersion=1.0
        DefaultDirName={pf}\kvapp
        DisableProgramGroupPage=yes
        UninstallDisplayIcon={app}\age_cal.exe
        Compression=lzma
        SolidCompression=yes

        [Files]
        Source: downloaded_artifacts/age_cal.exe; DestDir: {app}; Flags: ignoreversion
        " > setup_script.iss
    - name: Create Output directory
      run: mkdir Output
    - name: Print current directory
      run: |
        echo "Current working directory: $PWD"
        dir  # List contents of current directory
    - name: Run Inno Setup compiler
      run: |
        Start-Process -FilePath "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" -ArgumentList "setup_script.iss" -NoNewWindow -Wait
    - name: Print current directory
      run: |
        echo "Current working directory: $PWD"
        dir  # List contents of current directory
    - name: List files in Output directory
      run: |
        echo "Listing files in Output directory:"
        dir Output
    - name: Upload Inno Setup installer artifact
      uses: actions/upload-artifact@v3
      with:
        name: setup_exe
        path: Output/setup.exe  # Adjust path to setup.exe output file
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'  # Replace with your Python version
    - name: Send email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.office365.com
        server_port: 465
        username: smtp@aarkglobalinc.com
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: GitHub Actions Email with Attachment
        body: This email contains an attachment.
        to: satyambhat@aarkglobalinc.com
        from: smtp@aarkglobalinc.com
        attachments: Output/setup.exe
