name: CI/CD Pipeline for Python Calculator

# Define the trigger for the workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs that make up the workflow
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Specify the version of Python to use

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run tests
      - name: Run tests
        run: |
          python -m unittest discover

  deploy:
    runs-on: windows-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Specify the version of Python to use

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
   
      - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: age_cal_exe
        path: dist/age_cal.exe    

      # Step 4: Deploy (placeholder step)
      - name: Deploy
        run: |
          echo "Deployment step - customize this step for your deployment process"
